#include <iostream>
#include "DFS.h"
#include "Perfect_Maze.h"
#include "tool.h"
// #include "backtrace.h"

#define MAX_SIZE 30
#define MIN_SIZE 1
using namespace std;

int main() {
    //signal(SIGSEGV, signal_handler);

    int row, col;
    get_input(row, MIN_SIZE, MAX_SIZE, "输入迷宫行数(1 ~ 30): ");
    get_input(col, MIN_SIZE, MAX_SIZE, "输入迷宫列数(1 ~ 30): ");
    Maze M(row, col);
    DFS dfs;

    Perfect_Maze P;
    P.generate(M);
    cout << "--------------------Maze generated by PM--------------------" << endl;
    M.print_node_all();

    cout << "--------------------Maze solved by DFS----------------------" << endl;
    dfs.solve(M);

    //在终端输出带颜色的路径 最后可以尝试在终端复现寻路过程(利用光标定位)
    //dfs.print_results(M);
    return 0;
}